version: '3'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin
    restart: always
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - ./data/pg:/data
